### ISSUE TITLE
Python 3 issues

### ISSUE THREAD

**Issue by cclauss** [IBM/pyxcli#3]
tox.ini is configured to run flake8 tests on Python 2 but not on Python 3.

flake8 testing of https://github.com/IBM/pyxcli on Python 3.6.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./pyxcli/client.py:206:34: F821 undefined name 'basestring'
        if isinstance(endpoints, basestring):
                                 ^

./pyxcli/client.py:226:34: F821 undefined name 'basestring'
        if isinstance(endpoints, basestring):
                                 ^

./pyxcli/response.py:106:29: F821 undefined name 'basestring'
        if isinstance(item, basestring):
                            ^

./pyxcli/response.py:108:37: F821 undefined name 'long'
        elif isinstance(item, (int, long)):
                                    ^

./pyxcli/transports.py:310:34: F821 undefined name 'basestring'
        if isinstance(endpoints, basestring):
                                 ^

./pyxcli/helpers/xml_util.py:52:24: F821 undefined name 'basestring'
    if isinstance(obj, basestring) or not use_repr:
                       ^
```

**Comment by wegotthekeys** [comment]
I have fixed the compatibility issues with PR [https://github.com/IBM/pyxcli/pull/9](https://github.com/IBM/pyxcli/pull/9)

**Comment by cclauss** [comment]
@wegotthekeys Those fixes work great for Python 3 but unfortunately they can break Python 2 in the process like if you have a real unicode string like __u"Lüsai"__ or a real long like __1L__.

Try something like this:
```Python
try:
    long
except NameError:
    long = int

try:
    basestring
except NameError:
    basestring = (str, )
```

By the way... I spent a decade living in Rochester, NY...  A great place to live!
